name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/financeapp:latest .
        
    # Log in to ACR
    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Push Docker Image to ACR
    - name: Push Docker Image to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/financeapp:latest

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/financeapp:latest
