name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/financeapp:latest .

      # Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/financeapp:latest

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ghcr.io/${{ github.repository_owner }}/financeapp:latest
          scm-do-build-during-deployment: false
          slot-name: 'production'  # Use 'production' or your slot name
          docker-registry-server-url: 'https://ghcr.io'
          docker-registry-server-user: ${{ github.actor }}
          docker-registry-server-password: ${{ secrets.GHCR_PAT }}
